import * as dto from "./dto";

type PathParamValue = string | number | boolean;
type PathParams = Record<string, PathParamValue>;

const createBuildPath =
  (path: string) =>
  (params: PathParams = {}) =>
    path.replace(/:([A-Za-z0-9_]+)/g, (_, key: string) => {
      const value = params[key];

      if (value === undefined) {
        throw new Error(`Missing path param: ${key}`);
      }

      return encodeURIComponent(String(value));
    });

export const apiContract = {
  registerPublic: {
    method: "post",
    path: "/pagar/v1/auth/register/public",
    buildPath: createBuildPath("/pagar/v1/auth/register/public"),
    requestFormat: "json",
    params: dto.jsonEndpointParamsSchema,
    query: dto.jsonEndpointQuerySchema,
    body: dto.registerPublicBodySchema,
    successResponse: dto.registerPublicSuccessResponseSchema,
    errorResponse: dto.registerPublicErrorResponseSchema,
  },
  registerSchool: {
    method: "post",
    path: "/pagar/v1/auth/register/school",
    buildPath: createBuildPath("/pagar/v1/auth/register/school"),
    requestFormat: "json",
    params: dto.jsonEndpointParamsSchema,
    query: dto.jsonEndpointQuerySchema,
    body: dto.registerSchoolBodySchema,
    successResponse: dto.registerSchoolSuccessResponseSchema,
    errorResponse: dto.registerSchoolErrorResponseSchema,
  },
  registerSppg: {
    method: "post",
    path: "/pagar/v1/auth/register/sppg",
    buildPath: createBuildPath("/pagar/v1/auth/register/sppg"),
    requestFormat: "json",
    params: dto.jsonEndpointParamsSchema,
    query: dto.jsonEndpointQuerySchema,
    body: dto.registerSppgBodySchema,
    successResponse: dto.registerSppgSuccessResponseSchema,
    errorResponse: dto.registerSppgErrorResponseSchema,
  },
  login: {
    method: "post",
    path: "/pagar/v1/auth/login",
    buildPath: createBuildPath("/pagar/v1/auth/login"),
    requestFormat: "json",
    params: dto.jsonEndpointParamsSchema,
    query: dto.jsonEndpointQuerySchema,
    body: dto.loginBodySchema,
    successResponse: dto.loginSuccessResponseSchema,
    errorResponse: dto.loginErrorResponseSchema,
  },
  getPendingAccounts: {
    method: "get",
    path: "/pagar/v1/admin/accounts/pending",
    buildPath: createBuildPath("/pagar/v1/admin/accounts/pending"),
    requestFormat: "json",
    headers: dto.protectedHeadersSchema,
    params: dto.jsonEndpointParamsSchema,
    query: dto.paginatedListQuerySchema,
    successResponse: dto.getPendingAccountsSuccessResponseSchema,
    errorResponse: dto.getPendingAccountsErrorResponseSchema,
  },
  getActiveAccounts: {
    method: "get",
    path: "/pagar/v1/admin/accounts/active",
    buildPath: createBuildPath("/pagar/v1/admin/accounts/active"),
    requestFormat: "json",
    headers: dto.protectedHeadersSchema,
    params: dto.jsonEndpointParamsSchema,
    query: dto.paginatedListQuerySchema,
    successResponse: dto.getActiveAccountsSuccessResponseSchema,
    errorResponse: dto.getActiveAccountsErrorResponseSchema,
  },
  getAllSppg: {
    method: "get",
    path: "/pagar/v1/admin/sppgs",
    buildPath: createBuildPath("/pagar/v1/admin/sppgs"),
    requestFormat: "json",
    headers: dto.protectedHeadersSchema,
    params: dto.jsonEndpointParamsSchema,
    query: dto.paginatedListQuerySchema,
    successResponse: dto.getAllSppgSuccessResponseSchema,
    errorResponse: dto.getAllSppgErrorResponseSchema,
  },
  getAllSchool: {
    method: "get",
    path: "/pagar/v1/admin/schools",
    buildPath: createBuildPath("/pagar/v1/admin/schools"),
    requestFormat: "json",
    headers: dto.protectedHeadersSchema,
    params: dto.jsonEndpointParamsSchema,
    query: dto.paginatedListQuerySchema,
    successResponse: dto.getAllSchoolSuccessResponseSchema,
    errorResponse: dto.getAllSchoolErrorResponseSchema,
  },
  updateAccountStatus: {
    method: "patch",
    path: "/pagar/v1/admin/accounts/:id_user/status",
    buildPath: createBuildPath("/pagar/v1/admin/accounts/:id_user/status"),
    requestFormat: "json",
    headers: dto.protectedHeadersSchema,
    params: dto.updateAccountStatusParamsSchema,
    query: dto.jsonEndpointQuerySchema,
    body: dto.updateAccountStatusBodySchema,
    successResponse: dto.updateAccountStatusSuccessResponseSchema,
    errorResponse: dto.updateAccountStatusErrorResponseSchema,
  },
  updateProfile: {
    method: "patch",
    path: "/pagar/v1/admin/accounts/profile",
    buildPath: createBuildPath("/pagar/v1/admin/accounts/profile"),
    requestFormat: "json",
    headers: dto.protectedHeadersSchema,
    params: dto.jsonEndpointParamsSchema,
    query: dto.jsonEndpointQuerySchema,
    body: dto.updateAdminProfileBodySchema,
    successResponse: dto.updateAdminProfileSuccessResponseSchema,
    errorResponse: dto.updateAdminProfileErrorResponseSchema,
  },
  getDashboard: {
    method: "get",
    path: "/pagar/v1/admin/dashboard",
    buildPath: createBuildPath("/pagar/v1/admin/dashboard"),
    requestFormat: "json",
    headers: dto.protectedHeadersSchema,
    params: dto.jsonEndpointParamsSchema,
    query: dto.jsonEndpointQuerySchema,
    successResponse: dto.getAdminDashboardSuccessResponseSchema,
    errorResponse: dto.getAdminDashboardErrorResponseSchema,
  },
  updateReviewStatus: {
    method: "patch",
    path: "/pagar/v1/admin/reviews/:id_review/status",
    buildPath: createBuildPath("/pagar/v1/admin/reviews/:id_review/status"),
    requestFormat: "json",
    headers: dto.protectedHeadersSchema,
    params: dto.updateReviewStatusParamsSchema,
    query: dto.jsonEndpointQuerySchema,
    body: dto.updateReviewStatusBodySchema,
    successResponse: dto.updateReviewStatusSuccessResponseSchema,
    errorResponse: dto.updateReviewStatusErrorResponseSchema,
  },
  getPublicSppgList: {
    method: "get",
    path: "/pagar/v1/public/sppg_list",
    buildPath: createBuildPath("/pagar/v1/public/sppg_list"),
    requestFormat: "json",
    headers: dto.protectedHeadersSchema,
    params: dto.jsonEndpointParamsSchema,
    query: dto.jsonEndpointQuerySchema,
    successResponse: dto.getPublicSppgListSuccessResponseSchema,
    errorResponse: dto.getPublicSppgListErrorResponseSchema,
  },
  createPublicReview: {
    method: "post",
    path: "/pagar/v1/public/reviews",
    buildPath: createBuildPath("/pagar/v1/public/reviews"),
    requestFormat: "multipart/form-data",
    headers: dto.protectedHeadersSchema,
    params: dto.jsonEndpointParamsSchema,
    query: dto.jsonEndpointQuerySchema,
    body: dto.createPublicReviewBodySchema,
    files: dto.createPublicReviewFilesSchema,
    successResponse: dto.createPublicReviewSuccessResponseSchema,
    errorResponse: dto.createPublicReviewErrorResponseSchema,
  },
  getPublicDashboardReviews: {
    method: "get",
    path: "/pagar/v1/public/dashboard/reviews",
    buildPath: createBuildPath("/pagar/v1/public/dashboard/reviews"),
    requestFormat: "json",
    headers: dto.protectedHeadersSchema,
    params: dto.jsonEndpointParamsSchema,
    query: dto.jsonEndpointQuerySchema,
    successResponse: dto.getPublicDashboardReviewsSuccessResponseSchema,
    errorResponse: dto.getPublicDashboardReviewsErrorResponseSchema,
  },
  getPublicDashboardSppgReports: {
    method: "get",
    path: "/pagar/v1/public/dashboard/sppg_reports",
    buildPath: createBuildPath("/pagar/v1/public/dashboard/sppg_reports"),
    requestFormat: "json",
    headers: dto.protectedHeadersSchema,
    params: dto.jsonEndpointParamsSchema,
    query: dto.jsonEndpointQuerySchema,
    successResponse: dto.getPublicDashboardSppgReportsSuccessResponseSchema,
    errorResponse: dto.getPublicDashboardSppgReportsErrorResponseSchema,
  },
  getDetailSppgReport: {
    method: "get",
    path: "/pagar/v1/public/dashboard/sppg_reports/:id_daily_report",
    buildPath: createBuildPath(
      "/pagar/v1/public/dashboard/sppg_reports/:id_daily_report",
    ),
    requestFormat: "json",
    headers: dto.protectedHeadersSchema,
    params: dto.getDetailSppgReportParamsSchema,
    query: dto.jsonEndpointQuerySchema,
    successResponse: dto.getDetailSppgReportSuccessResponseSchema,
    errorResponse: dto.getDetailSppgReportErrorResponseSchema,
  },
  getSchoolProfile: {
    method: "get",
    path: "/pagar/v1/school/profile",
    buildPath: createBuildPath("/pagar/v1/school/profile"),
    requestFormat: "json",
    headers: dto.protectedHeadersSchema,
    params: dto.jsonEndpointParamsSchema,
    query: dto.jsonEndpointQuerySchema,
    successResponse: dto.getSchoolProfileSuccessResponseSchema,
    errorResponse: dto.getSchoolProfileErrorResponseSchema,
  },
  updateSchoolProfile: {
    method: "put",
    path: "/pagar/v1/school/profile",
    buildPath: createBuildPath("/pagar/v1/school/profile"),
    requestFormat: "json",
    headers: dto.protectedHeadersSchema,
    params: dto.jsonEndpointParamsSchema,
    query: dto.jsonEndpointQuerySchema,
    body: dto.updateSchoolProfileBodySchema,
    successResponse: dto.updateSchoolProfileSuccessResponseSchema,
    errorResponse: dto.updateSchoolProfileErrorResponseSchema,
  },
  getSchoolSppgList: {
    method: "get",
    path: "/pagar/v1/school/sppg_list",
    buildPath: createBuildPath("/pagar/v1/school/sppg_list"),
    requestFormat: "json",
    headers: dto.protectedHeadersSchema,
    params: dto.jsonEndpointParamsSchema,
    query: dto.schoolPaginatedListQuerySchema,
    successResponse: dto.getSchoolSppgListSuccessResponseSchema,
    errorResponse: dto.getSchoolSppgListErrorResponseSchema,
  },
  getSchoolDailyReports: {
    method: "get",
    path: "/pagar/v1/school/daily_report",
    buildPath: createBuildPath("/pagar/v1/school/daily_report"),
    requestFormat: "json",
    headers: dto.protectedHeadersSchema,
    params: dto.jsonEndpointParamsSchema,
    query: dto.schoolPaginatedListQuerySchema,
    successResponse: dto.getSchoolDailyReportsSuccessResponseSchema,
    errorResponse: dto.getSchoolDailyReportsErrorResponseSchema,
  },
  createSchoolReview: {
    method: "post",
    path: "/pagar/v1/school/review",
    buildPath: createBuildPath("/pagar/v1/school/review"),
    requestFormat: "multipart/form-data",
    headers: dto.protectedHeadersSchema,
    params: dto.jsonEndpointParamsSchema,
    query: dto.jsonEndpointQuerySchema,
    body: dto.createSchoolReviewBodySchema,
    files: dto.createSchoolReviewFilesSchema,
    successResponse: dto.createSchoolReviewSuccessResponseSchema,
    errorResponse: dto.createSchoolReviewErrorResponseSchema,
  },
  getSchoolDashboardReviews: {
    method: "get",
    path: "/pagar/v1/school/dashboard/reviews",
    buildPath: createBuildPath("/pagar/v1/school/dashboard/reviews"),
    requestFormat: "json",
    headers: dto.protectedHeadersSchema,
    params: dto.jsonEndpointParamsSchema,
    query: dto.schoolPaginatedListQuerySchema,
    successResponse: dto.getSchoolDashboardReviewsSuccessResponseSchema,
    errorResponse: dto.getSchoolDashboardReviewsErrorResponseSchema,
  },
  getSchoolDashboardSppgReports: {
    method: "get",
    path: "/pagar/v1/school/dashboard/sppg_reports",
    buildPath: createBuildPath("/pagar/v1/school/dashboard/sppg_reports"),
    requestFormat: "json",
    headers: dto.protectedHeadersSchema,
    params: dto.jsonEndpointParamsSchema,
    query: dto.schoolPaginatedListQuerySchema,
    successResponse: dto.getSchoolDashboardSppgReportsSuccessResponseSchema,
    errorResponse: dto.getSchoolDashboardSppgReportsErrorResponseSchema,
  },
  getSppgProfile: {
    method: "get",
    path: "/pagar/v1/sppg/profile",
    buildPath: createBuildPath("/pagar/v1/sppg/profile"),
    requestFormat: "json",
    headers: dto.protectedHeadersSchema,
    params: dto.jsonEndpointParamsSchema,
    query: dto.jsonEndpointQuerySchema,
    successResponse: dto.getSppgProfileSuccessResponseSchema,
    errorResponse: dto.getSppgProfileErrorResponseSchema,
  },
  updateSppgProfile: {
    method: "put",
    path: "/pagar/v1/sppg/profile",
    buildPath: createBuildPath("/pagar/v1/sppg/profile"),
    requestFormat: "json",
    headers: dto.protectedHeadersSchema,
    params: dto.jsonEndpointParamsSchema,
    query: dto.jsonEndpointQuerySchema,
    body: dto.updateSppgProfileBodySchema,
    successResponse: dto.updateSppgProfileSuccessResponseSchema,
    errorResponse: dto.updateSppgProfileErrorResponseSchema,
  },
  getSppgDashboard: {
    method: "get",
    path: "/pagar/v1/sppg/dashboard",
    buildPath: createBuildPath("/pagar/v1/sppg/dashboard"),
    requestFormat: "json",
    headers: dto.protectedHeadersSchema,
    params: dto.jsonEndpointParamsSchema,
    query: dto.jsonEndpointQuerySchema,
    successResponse: dto.getSppgDashboardSuccessResponseSchema,
    errorResponse: dto.getSppgDashboardErrorResponseSchema,
  },
  getSppgDailyReports: {
    method: "get",
    path: "/pagar/v1/sppg/daily_reports",
    buildPath: createBuildPath("/pagar/v1/sppg/daily_reports"),
    requestFormat: "json",
    headers: dto.protectedHeadersSchema,
    params: dto.jsonEndpointParamsSchema,
    query: dto.paginatedListQuerySchema,
    successResponse: dto.getSppgDailyReportsSuccessResponseSchema,
    errorResponse: dto.getSppgDailyReportsErrorResponseSchema,
  },
  createSppgDailyReport: {
    method: "post",
    path: "/pagar/v1/sppg/daily_report",
    buildPath: createBuildPath("/pagar/v1/sppg/daily_report"),
    requestFormat: "multipart/form-data",
    headers: dto.protectedHeadersSchema,
    params: dto.jsonEndpointParamsSchema,
    query: dto.jsonEndpointQuerySchema,
    body: dto.createSppgDailyReportBodySchema,
    files: dto.createSppgDailyReportFilesSchema,
    successResponse: dto.createSppgDailyReportSuccessResponseSchema,
    errorResponse: dto.createSppgDailyReportErrorResponseSchema,
  },
  getSppgPeriodicReports: {
    method: "get",
    path: "/pagar/v1/sppg/periodic_reports",
    buildPath: createBuildPath("/pagar/v1/sppg/periodic_reports"),
    requestFormat: "json",
    headers: dto.protectedHeadersSchema,
    params: dto.jsonEndpointParamsSchema,
    query: dto.getSppgPeriodicReportsQuerySchema,
    successResponse: dto.getSppgPeriodicReportsSuccessResponseSchema,
    errorResponse: dto.getSppgPeriodicReportsErrorResponseSchema,
  },
  getSppgDailyReportById: {
    method: "get",
    path: "/pagar/v1/sppg/daily_report/:id_daily_report",
    buildPath: createBuildPath("/pagar/v1/sppg/daily_report/:id_daily_report"),
    requestFormat: "json",
    headers: dto.protectedHeadersSchema,
    params: dto.getSppgDailyReportByIdParamsSchema,
    query: dto.jsonEndpointQuerySchema,
    successResponse: dto.getSppgDailyReportByIdSuccessResponseSchema,
    errorResponse: dto.getSppgDailyReportByIdErrorResponseSchema,
  },
  updateSppgMonthlyBudget: {
    method: "patch",
    path: "/pagar/v1/sppg/monthly-budget",
    buildPath: createBuildPath("/pagar/v1/sppg/monthly-budget"),
    requestFormat: "json",
    headers: dto.protectedHeadersSchema,
    params: dto.jsonEndpointParamsSchema,
    query: dto.jsonEndpointQuerySchema,
    body: dto.updateSppgMonthlyBudgetBodySchema,
    successResponse: dto.updateSppgMonthlyBudgetSuccessResponseSchema,
    errorResponse: dto.updateSppgMonthlyBudgetErrorResponseSchema,
  },
} as const;

export type ApiContract = typeof apiContract;
